module.exports.busRoutes = [
    { 'source': 'Ahmedabad', 'destination': 'Surat' },
    { 'source': 'Vadodara', 'destination': 'Rajkot' },
    { 'source': 'Surat', 'destination': 'Valsad' },
    { 'source': 'Bhavnagar', 'destination': 'Jamnagar' },
    { 'source': 'Amreli', 'destination': 'Junagadh' },
    { 'source': 'Kheda', 'destination': 'Mehsana' },
    { 'source': 'Dahod', 'destination': 'Patan' },
    { 'source': 'Narmada', 'destination': 'Navsari' },
    { 'source': 'Gandhinagar', 'destination': 'Morbi' },
    { 'source': 'Panchmahal', 'destination': 'Banaskantha' },
    { 'source': 'Porbandar', 'destination': 'Devbhoomi Dwarka' },
    { 'source': 'Valsad', 'destination': 'Anand' },
    { 'source': 'Tapi', 'destination': 'Surendranagar' },
    { 'source': 'Vadodara', 'destination': 'Dahod' },
    { 'source': 'Sabarkantha', 'destination': 'Botad' },
    { 'source': 'Mahisagar', 'destination': 'Dang' },
    { 'source': 'Surat', 'destination': 'Gandhinagar' },
    { 'source': 'Kutch', 'destination': 'Mehsana' },
    { 'source': 'Bhavnagar', 'destination': 'Ahmedabad' },
    { 'source': 'Junagadh', 'destination': 'Jamnagar' },
    { 'source': 'Aravalli', 'destination': 'Chhota Udaipur' },
    { 'source': 'Banaskantha', 'destination': 'Sabarkantha' },
    { 'source': 'Patan', 'destination': 'Vadodara' },
    { 'source': 'Rajkot', 'destination': 'Kheda' },
    { 'source': 'Surendranagar', 'destination': 'Bharuch' },
    { 'source': 'Botad', 'destination': 'Valsad' },
    { 'source': 'Navsari', 'destination': 'Dahod' },
    { 'source': 'Ahmedabad', 'destination': 'Mahisagar' },
    { 'source': 'Devbhoomi Dwarka', 'destination': 'Tapi' },
    { 'source': 'Jamnagar', 'destination': 'Mehsana' },
    { 'source': 'Narmada', 'destination': 'Rajkot' },
    { 'source': 'Amreli', 'destination': 'Panchmahal' },
    { 'source': 'Morbi', 'destination': 'Vadodara' },
    { 'source': 'Sabarkantha', 'destination': 'Botad' },
    { 'source': 'Valsad', 'destination': 'Banaskantha' },
    { 'source': 'Surat', 'destination': 'Kutch' },
    { 'source': 'Gandhinagar', 'destination': 'Surendranagar' },
    { 'source': 'Dang', 'destination': 'Porbandar' },
    { 'source': 'Bharuch', 'destination': 'Aravalli' },
    { 'source': 'Patan', 'destination': 'Junagadh' },
    { 'source': 'Navsari', 'destination': 'Bhavnagar' },
    { 'source': 'Rajkot', 'destination': 'Anand' },
    { 'source': 'Vadodara', 'destination': 'Surat' },
    { 'source': 'Banaskantha', 'destination': 'Mahisagar' },
    { 'source': 'Ahmedabad', 'destination': 'Devbhoomi Dwarka' },
    { 'source': 'Botad', 'destination': 'Amreli' },
    { 'source': 'Tapi', 'destination': 'Panchmahal' },
    { 'source': 'Mehsana', 'destination': 'Valsad' },
    { 'source': 'Dahod', 'destination': 'Kheda' },
    { 'source': 'Surendranagar', 'destination': 'Gandhinagar' },
    { 'source': 'Ahmedabad', 'destination': 'Bhavnagar' },
    { 'source': 'Surat', 'destination': 'Vadodara' },
    { 'source': 'Rajkot', 'destination': 'Jamnagar' },
    { 'source': 'Valsad', 'destination': 'Bharuch' },
    { 'source': 'Kutch', 'destination': 'Surendranagar' },
    { 'source': 'Gandhinagar', 'destination': 'Narmada' },
    { 'source': 'Amreli', 'destination': 'Tapi' },
    { 'source': 'Junagadh', 'destination': 'Mehsana' },
    { 'source': 'Panchmahal', 'destination': 'Banaskantha' },
    { 'source': 'Kheda', 'destination': 'Navsari' },
    { 'source': 'Morbi', 'destination': 'Botad' },
    { 'source': 'Dahod', 'destination': 'Chhota Udaipur' },
    { 'source': 'Surat', 'destination': 'Porbandar' },
    { 'source': 'Sabarkantha', 'destination': 'Devbhoomi Dwarka' },
    { 'source': 'Vadodara', 'destination': 'Dang' },
    { 'source': 'Aravalli', 'destination': 'Ahmedabad' },
    { 'source': 'Patan', 'destination': 'Valsad' },
    { 'source': 'Bhavnagar', 'destination': 'Anand' },
    { 'source': 'Surendranagar', 'destination': 'Banaskantha' },
    { 'source': 'Jamnagar', 'destination': 'Gandhinagar' },
    { 'source': 'Mahisagar', 'destination': 'Mehsana' },
    { 'source': 'Botad', 'destination': 'Kutch' },
    { 'source': 'Dahod', 'destination': 'Amreli' },
    { 'source': 'Navsari', 'destination': 'Vadodara' },
    { 'source': 'Tapi', 'destination': 'Rajkot' },
    { 'source': 'Narmada', 'destination': 'Surat' },
    { 'source': 'Chhota Udaipur', 'destination': 'Patan' },
    { 'source': 'Bharuch', 'destination': 'Kheda' },
    { 'source': 'Banaskantha', 'destination': 'Porbandar' },
    { 'source': 'Devbhoomi Dwarka', 'destination': 'Jamnagar' },
    { 'source': 'Morbi', 'destination': 'Dahod' },
    { 'source': 'Ahmedabad', 'destination': 'Sabarkantha' },
    { 'source': 'Vadodara', 'destination': 'Mehsana' },
    { 'source': 'Valsad', 'destination': 'Bhavnagar' },
    { 'source': 'Surat', 'destination': 'Junagadh' },
    { 'source': 'Amreli', 'destination': 'Navsari' },
    { 'source': 'Tapi', 'destination': 'Banaskantha' },
    { 'source': 'Aravalli', 'destination': 'Rajkot' },
    { 'source': 'Mahisagar', 'destination': 'Botad' },
    { 'source': 'Surendranagar', 'destination': 'Chhota Udaipur' },
    { 'source': 'Sabarkantha', 'destination': 'Dang' },
    { 'source': 'Porbandar', 'destination': 'Ahmedabad' },
    { 'source': 'Jamnagar', 'destination': 'Anand' },
    { 'source': 'Panchmahal', 'destination': 'Devbhoomi Dwarka' },
    { 'source': 'Mehsana', 'destination': 'Patan' },
    { 'source': 'Bhavnagar', 'destination': 'Dahod' },
    { 'source': 'Navsari', 'destination': 'Surat' },
    { 'source': 'Kheda', 'destination': 'Valsad' },
    { 'source': 'Anand', 'destination': 'Gandhinagar' },
    { 'source': 'Dang', 'destination': 'Mahisagar' },
    { 'source': 'Kutch', 'destination': 'Bharuch' }
];
